# Generated by Django 4.2 on 2024-05-31 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='Proveedor'),
        ),
    ]
